// client/src/app/views/home/home.component.ts
import { HttpHeaders } from '@angular/common/http';
import { Component, OnDestroy, OnInit } from '@angular/core';
import { ToastrService } from 'ngx-toastr';
import { Subject, timer } from 'rxjs';
import { switchMap, take, takeUntil } from 'rxjs/operators';
import { Category } from 'src/app/models/Category';
import { Channel } from 'src/app/models/Channel';
import { HomeSettings } from 'src/app/models/HomeSettings';
import { PlaySoundRequest } from 'src/app/models/PlaySoundRequest';
import { Server } from 'src/app/models/Server';
import { SoundMeta } from 'src/app/models/SoundMeta';
import { Sounds } from 'src/app/models/Sounds';
import { ToastTitles } from 'src/app/models/ToastTitles';
import { AuthService } from 'src/app/services/auth.service';
import { DataService } from 'src/app/services/data.service';
import { StorageService } from 'src/app/services/storage.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit, OnDestroy {
  public servers: Server[] = [];
  public sounds: Sounds | undefined;
  public channels: Channel[] = [];
  public soundCategories: Category[] = [];
  public selectedCategory?: string;
  public maxVolume = 1;
  public youtubeUrl = '';
  public searchText = '';
  public settings: HomeSettings = new HomeSettings();
  public soundPollingInterval = 30 * 1000;
  private destroyed$: Subject<void> = new Subject<void>();
  private serverChanged$: Subject<void> = new Subject<void>();
  public loading: boolean = true;

  public get isOwner(): boolean {
    return this.authService.isOwner();
  }

  public get selectedServerId(): string | undefined {
    return this.settings.selectedServerId;
  }

  public set selectedServerId(serverId: string | undefined) {
    this.settings.selectedServerId = serverId;
    this.saveSettings();
    this.serverChanged$.next();
  }

  public get joinUser(): boolean {
    return this.settings.joinUser;
  }

  public set joinUser(joinUser: boolean) {
    this.settings.joinUser = joinUser;
    this.saveSettings();
  }

  public get selectedChannelId(): string | undefined {
    return this.settings.selectedChannelId;
  }

  public set selectedChannelId(channelId: string | undefined) {
    this.settings.selectedChannelId = channelId;
    this.saveSettings();
  }

  public get volume(): number {
    return this.settings.volume;
  }

  public set volume(vol: number) {
    this.settings.volume = vol;
    this.saveSettings();
  }

  public get userId(): string | undefined {
    return this.storageService.payload?.id;
  }

  public get filteredSoundCategories(): Category[] {
    return this.soundCategories.filter(category =>{
      return this.filteredSounds(category.name).length > 0;
    });
  }

  constructor(private readonly authService: AuthService, private readonly storageService: StorageService, private readonly dataService: DataService, private readonly toast: ToastrService) { }

  public ngOnInit(): void {
    this.loadSettings();

    if(this.isOwner) {
      this.maxVolume = 1000;
    }

    this.serverChanged$
      .pipe(
        takeUntil(this.destroyed$)
      ).subscribe(_ => {
        this.selectedChannelId = undefined;
        if(this.selectedServerId) {
          this.fetchChannels();
          this.dataService.loadSounds(this.selectedServerId);
        }
      })

    timer(this.soundPollingInterval, this.soundPollingInterval).pipe(
      takeUntil(this.destroyed$),
    ).subscribe(() => {
      if(this.selectedServerId) {
        this.dataService.loadSounds(this.selectedServerId, new Date());
      }
    });

    this.dataService.sounds.pipe(
      takeUntil(this.destroyed$)
    ).subscribe(newSounds => {
      this.sounds = newSounds;
      this.updateSoundCategories(this.sounds);
    });

    this.dataService.servers.pipe(
      takeUntil(this.destroyed$)
    ).subscribe(servers => {
      this.servers = servers;
      if(!this.selectedServerId || !this.servers.some(server => server.id === this.selectedServerId)) {
        this.selectedServerId = this.servers.find(_ => true)?.id;
      }
      else if(!this.sounds) {
        this.dataService.loadSounds(this.selectedServerId);
      }
      this.loading = false;
      this.fetchChannels();
    });

    this.dataService.channels.pipe(
      takeUntil(this.destroyed$)
    ).subscribe(channels => {
      this.channels = channels;
      if(!this.selectedChannelId || !this.channels.some(channel => channel.id === this.selectedChannelId)) {
        this.selectedChannelId = channels.find(_ => true)?.id;
      }
    })

    this.dataService.loadServers();
  }

  private updateSoundCategories(sounds: Sounds): void {
    this.soundCategories = Object.keys(sounds).map(category => {
      return {
        name: category,
        show: !!this.soundCategories.find(cat => cat.name === category)?.show
      };
    });
    if(!this.selectedCategory || !this.soundCategories.some(category => category.name === this.selectedCategory)) {
      this.selectedCategory = this.soundCategories.find(_ => true)?.name;
    }
  }

  public isAdmin(): boolean {
    return this.servers.find(server => server.id === this.selectedServerId)?.isAdmin ?? false;
  }

  public fetchChannels(): void {
    if(this.selectedServerId) {
      this.dataService.loadChannels(this.selectedServerId);
    }
  }

  public loadSettings(): void {
    this.settings = this.storageService.settings;
  }

  public saveSettings(): void {
    this.storageService.settings = this.settings;
  }

  public submitFile(files: FileList | null): void {
    if(files && this.selectedCategory && this.selectedServerId) {
      this.dataService.submitFile(files, this.selectedCategory, this.selectedServerId).subscribe(() => {
        //maybe show a loading-spinner
      });
    }
  }

  public setCategoriesVisibility(status: boolean): void {
    for(const category of this.soundCategories) {
      category.show = status;
    }
  }

  public playSound(soundId?: string, forcePlay = false): void {
    if(this.selectedServerId && this.selectedChannelId && (soundId || this.youtubeUrl)) {
      const request = new PlaySoundRequest(
          soundId,
          forcePlay,
          this.selectedServerId,
          this.selectedChannelId,
          this.volume,
          this.joinUser,
          this.youtubeUrl
        );
      this.dataService.playSound(request).subscribe();
    }
  }

  public playFile(soundId: string, audioElement: HTMLAudioElement): void {
    if(!audioElement.src){
      this.dataService.downloadSound(soundId).subscribe(response =>{
        try{
          audioElement.pause();
          audioElement.src = URL.createObjectURL(response.body);
          audioElement.title = this.getFileNameOutOfHeader(response.headers);
          audioElement.play();
        }
        catch{
          this.toast.error(`Konn de Datei nit obspüln\nFormat weat onscheinend nit unterstützt`, ToastTitles.ERROR);
        }
      });
    }
  }

  public downloadSound(soundId: string, audioElement: HTMLAudioElement): void {
    if(audioElement.src) {
      this.downloadFile(audioElement.src, audioElement.title);
    }
    else {
      this.dataService.downloadSound(soundId).subscribe(response => {
        if(response.body) {
          this.downloadFile(response.body, this.getFileNameOutOfHeader(response.headers));
        }
        else {
          this.toast.error('Konnst du ma bitte sogn, warum i jetz nix hinta kriag hob?', ToastTitles.ERROR);
        }
      })
    }
  }

  private downloadFile(data: Blob | string, fileName: string) {
    const url: string = data instanceof Blob ? window.URL.createObjectURL(data) : data;
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', fileName);
    document.body.appendChild(link);
    link.click();
  }

  private getFileNameOutOfHeader(headers: HttpHeaders){
    let fileName = '';
    const disposition = headers.get('content-disposition');
    if (disposition?.includes('attachment')) {
        const reg = /filename[^;=\n]*=((['"]).*?\2|[^;\n]*)/;
        const matches = reg.exec(disposition);
        if (matches?.[1]) { 
          fileName = matches[1].replace(/['"]/g, '');
        }
    }
    return fileName;
  }

  public stopPlaying(): void {
    if(this.selectedServerId) {
      this.dataService.stopPlaying(this.selectedServerId).subscribe(() => {
      });
    }
  }

  public setIntro(soundId: string) {
    if(this.selectedServerId) {
      this.dataService.updateIntro(soundId, this.selectedServerId).subscribe(() => {
      });
    }
  }

  public deleteSound(soundId: string, category: string): void {
    this.dataService.deleteSound(soundId).subscribe(() => {
      if(this.sounds)  {
        const index = this.sounds[category]?.findIndex(sound => sound._id === soundId);
        if(index >= 0) {
          this.sounds[category].splice(index, 1);
        }
      }
    });
  }

  public filteredSounds(category: string): SoundMeta[]{
    let sounds: SoundMeta[];
    if(this.sounds) {
      if(this.searchText.length > 0){
        const re = new RegExp(this.searchText,'i');
        sounds = this.sounds[category].filter(sound => re.test(sound.fileName) || (sound.username && re.test(sound.username)));
      }
      else{
        sounds = this.sounds[category];
      }
    }
    else {
      sounds = [];
    }
    return sounds;
  }

  public ngOnDestroy(): void {
    this.destroyed$.next();
    this.destroyed$.complete();
  }
}

<ng-container *ngIf="servers.length !== 0, else noServers">
    <div class="container" style="margin-top:50px">
        <div id="fetch" class="form-horizontal" >
            <h1 class="control-label">Server</h1>
            <div class="input-group">
                <select class="form-control" [(ngModel)]="selectedServerId">
                    <option *ngFor="let server of servers" [value]="server.id" [textContent]="server.name"></option>
                </select>
            </div>

            <h1>Sounds hochladen</h1>
            <div class="form-group">
                <label class="control-label">Wähle eine Kategorie aus</label>
                <div class="input-group">
                    <label class="btn btn-primary col-md-2 finger">
                        Auswahl der Datei(en) <input type="file" #inputFiles style="display:none" multiple accept="audio/*" (change)="submitFile(inputFiles.files); inputFiles.value = ''"/>
                    </label>
                    <input type="text"
                            placeholder="Pick one"
                            [(ngModel)]="selectedCategory"
                            matInput
                            [matAutocomplete]="auto">
                    <mat-autocomplete autoActiveFirstOption #auto="matAutocomplete">
                        <mat-option *ngFor="let category of soundCategories" [value]="category.name" [textContent]="category.name"></mat-option>
                    </mat-autocomplete>
                </div>
            </div>
                
            <h1>Sounds abspielen</h1>
            <div class="form-group ">
                <label class="control-label">Channel auswählen</label>
                <select class="form-control" [(ngModel)]="selectedChannelId">
                    <option *ngFor="let channel of channels" [value]="channel.id" [textContent]="channel.name"></option>
                </select>
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="joinUser" [(ngModel)]="joinUser">
                    <label class="form-check-label" for="joinUser">
                        Beim Benutzer joinen
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label">Laustärke (von 0,0-1)</label>
                <input class="form-control col-md-1" type="number" [(ngModel)]="volume" step="0.5" min="0" [max]="maxVolume">
            </div>
            
            <div class="form-group">
                <label class="control-label">Youtube URL</label>
                <div class="input-group">
                    <input class="form-control col-md-10" [(ngModel)]="youtubeUrl">
                    <button type="button" class="btn btn-primary col-md-2" (click)="playSound()">Abspielen</button>
                </div>
            </div>
            <div class="form-group">
                <button type="button" class="btn btn-primary" (click)="stopPlaying()">Abspielen stoppen</button>
            </div>
            <div class="form-group">
                <label class="control-label">Suche</label>
                <input class="form-control" [(ngModel)]="searchText">
            </div>
            <div class="form-group">
                <button type="button" class="btn btn-primary" (click)="setCategoriesVisibility(true)">Alle Kategorien erweitern</button>
                <button type="button" class="btn btn-primary" (click)="setCategoriesVisibility(false)">Alle Kategorien schließen</button>
            </div>
        </div>
    </div>
    <div *ngFor="let category of filteredSoundCategories" class="col-md-8" style="margin: 0 auto">
        <h2 class="control-label" [textContent]="category.name"></h2>
        <button type="button" class="btn btn-primary" (click)="category.show = !category.show" style="width: 40px; height: 40px" [textContent]="category.show ? '-' : '+'"></button>
        <div class="table_scroll">
            <table class="table text-break" *ngIf="category.show">
                <thead>
                    <tr>
                        <th style="min-width: 300px">Name</th>
                        <th style="min-width: 300px">Benutzer</th>
                        <th style="min-width: 380px">Abspielen</th>
                        <th style="min-width: 270px">Aktion</th>
                    </tr>
                </thead>
                <tbody>
                    <tr *ngFor="let sound of filteredSounds(category.name)">
                        <td [textContent]="sound.fileName"></td>
                        <td [textContent]="sound.username"></td>
                        <td>
                        <a *ngIf="!audioControl.src" [routerLink]="" (click)="playFile(sound._id, audioControl)" title="Laden">
                            <i class="fas fa-file-export"></i>
                        </a>
                        <audio controls #audioControl></audio>
                        </td>
                        <td>
                        <a [routerLink]="" *ngIf="isAdmin || isOwner" (click)="playSound(sound._id, true)" title="Abspielen ohne Unterbrechung">
                            <i class="fa fa-play"></i>
                        </a>
                        <a [routerLink]="" (click)="playSound(sound._id, false)" title="Abspielen">
                            <i class="far fa-play-circle"></i>
                        </a>
                        <a [routerLink]="" (click)="downloadSound(sound._id, audioControl)" title="Herunterladen">
                            <i class="fas fa-download"></i>
                        </a>
                        <a [routerLink]="" (click)="setIntro(sound._id)" title="Als Intro festlegen">
                            <i class="fas fa-save"></i>
                        </a>
                        <a [routerLink]="" (click)="deleteSound(sound._id, category.name)" title="Löschen" [class.disabled]="!(userId === sound.userId || isAdmin || isOwner)">
                            <i class="fas fa-trash-alt"></i>
                        </a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</ng-container>
<ng-template #noServers>
    <ng-container *ngIf="loading; then isLoading else empty"></ng-container>
    <ng-template #isLoading>Loading...</ng-template>
    <ng-template #empty>Du bist auf kan Server, wo da Bot a drauf is</ng-template>
</ng-template>

// src/views/Home.vue
<template>
    <div class="container" style="margin-top:50px">
        <div id="fetch" class="form-horizontal" >
            <button type="button" class="btn btn-primary" v-on:click="updateWebsite()" v-if="isOwner">Server aktualisieren</button>
            <h1 class="control-label">Server</h1>
            <div class="input-group">
                <select class="form-control" v-model="selectedServer" @change="setAdmin(); fetchChannels(); saveSettings(); fetchSounds()">
                    <option v-for="server in servers" :value="server.id" :key="server.id">
                        {{server.name}}
                    </option>
                </select>
            </div>

            <h1>Sounds hochladen</h1>
            <div class="form-group">
                <label class="control-label">Wähle eine Kategorie aus</label>
                <div class="input-group">
                    <label class="btn btn-primary col-md-2 finger">
                        Auswahl der Datei(en) <input type="file" style="display:none" multiple id="file" ref="file" accept="audio/*" v-on:change="submitFile()"/>
                    </label>
                    <typeahead class="col-md-10" :suggestions="soundCategories" item_key="name" :selection.sync="selectedCategory" />
                </div>
            </div>
                
            <h1>Sounds abspielen</h1>
            <div class="form-group ">
                <label class="control-label">Channel auswählen</label>
                <select class="form-control" v-model="selectedChannel"  @change="saveSettings()">
                    <option v-for="channel in channels" :value="channel.id" :key="channel">
                        {{channel.name}}
                    </option>
                </select>
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="joinUser" v-model="joinUser" @change="saveSettings()" >
                    <label class="form-check-label" for="joinUser">
                        Beim Benutzer joinen
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label">Laustärke (von 0,0-1)</label>
                <input class="form-control col-md-1" type="number" v-model="volume" step="0.5" :max="maxVolume"  @change="saveSettings()">
            </div>
            
            <div class="form-group">
                <label class="control-label">Youtube URL</label>
                <div class="input-group">
                    <input class="form-control col-md-10" v-model="youtubeUrl">
                    <button type="button" class="btn btn-primary col-md-2" v-on:click="playSound()">Abspielen</button>
                </div>
            </div>
            <div class="form-group">
                <button type="button" class="btn btn-primary" v-on:click="stopPlaying()">Abspielen stoppen</button>
            </div>
            <div class="form-group">
                <label class="control-label">Suche</label>
                <input class="form-control" v-model="searchText">
            </div>
            <div class="form-group">
                <button type="button" class="btn btn-primary" v-on:click="setCategoriesVisibility(true)">Alle Kategorien erweitern</button>
                <button type="button" class="btn btn-primary" v-on:click="setCategoriesVisibility(false)">Alle Kategorien schließen</button>
            </div>
            
            <div v-for="category in filteredSoundCategories" :key="category.name">
                <h2 class="control-label">{{category.name}}</h2>
                <button type="button" class="btn btn-primary" v-on:click="changeCategoryVisibility(category)" style="width: 40px; height: 40px">{{category.show ? '-' : '+'}}</button>
                <table class="table text-break" v-show="category.show">
                    <thead>
                        <tr>
                            <th style="width: 300px">Name</th>
                            <th>Benutzer</th>
                            <th style="width: 380px">Abspielen</th>
                            <th style="width: 270px">Aktion</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="(sound, $index) in filteredSounds(category.name)" :key="sound.id">
                            <td>
                                {{sound.fileName}}
                            </td>
                            <td>
                                {{sound.user.name}}
                            </td>
                            <td>
                              <a href="#" @click.prevent="playFile(sound.id)" title="Laden">
                                <i class="fa fa-sync"></i>
                              </a>
                              <audio controls :ref="`audio_${sound.id}`">
                              </audio>
                            </td>
                            <td>
                              <a href="#" v-if="isAdmin || isOwner" @click.prevent="playSound(sound.id, true)" title="Abspielen ohne Unterbrechung">
                                <i class="fa fa-play"></i>
                              </a>
                              <a href="#" @click.prevent="playSound(sound.id)" title="Abspielen">
                                <i class="far fa-play-circle"></i>
                              </a>
                              <a href="#" @click.prevent="downloadSound(sound.id)" title="Herunterladen">
                                <i class="fas fa-download"></i>
                              </a>
                              <a href="#" @click.prevent="setIntro(sound.id)" title="Als Intro festlegen">
                                <i class="fas fa-save"></i>
                              </a>
                              <a href="#" @click.prevent="deleteSound(sound.id, $index, category.name)" title="Löschen" :class="userId == sound.user.id || isAdmin || isOwner ? '' : 'disabled'">
                                <i class="fas fa-trash-alt"></i>
                              </a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</template>
<script>

import dataservice from '../services/dataservice';
import settings from '../services/settings';

export default {
  data() {
    return {
      servers: [],
      sounds: {},
      channels: [],
      soundCategories: [],
      volume: 0.5,
      selectedCategory: undefined,
      selectedServer: undefined,
      selectedChannel: undefined,
      isOwner: false,
      maxVolume: 1,
      joinUser: true,
      youtubeUrl: undefined,
      searchText: '',
      userId: undefined,
      isAdmin: false
    };
  },
  computed:{
    filteredSoundCategories(){
      return this.soundCategories.filter(category =>{
        return this.filteredSounds(category.name).length > 0;
      })
    }
  },
  async created() {
      await this.fetchServers();
      this.loadSettings();
      const decodedToken = this.$auth.getDecodedToken();
      if(decodedToken){
        this.userId = decodedToken.id;
        this.isOwner = decodedToken.owner;
        if(this.isOwner){
            this.maxVolume = 100;
        }
      }
      if(this.selectedServer){
        this.fetchSounds();
      }
      this.setAdmin();
  },
  methods: {
    setAdmin(){
      this.isAdmin = this.servers.filter(server => server.id == this.selectedServer)[0].admin;
    },
    async fetchServers() {
      try{
        const response = await dataservice.fetchServers()
        this.servers = response.data;
        this.selectedServer = this.servers[0].id;
      }
      catch{
          this.$bvToast.toast(`Konn de Channels nit lodn. Ka wos do los is`, {
            title: 'Fehler',
            autoHideDelay: this.$config.toastDelay,
            variant: 'danger',
            appendToast: true
          });
      }
    },
    async submitFile(){
      const selectedCat = this.selectedCategory;
      if(selectedCat){
        let formData = new FormData();
        formData.append('category', selectedCat);
        formData.append('serverId', this.selectedServer)
        for(let i = 0; i < this.$refs.file.files.length; i++){
          formData.append(`files`,this.$refs.file.files[i]);
        }
        this.$refs.file.value = '';
        try{
          await dataservice.uploadFile(formData);
          if(!this.sounds[selectedCat]){
            this.$set(this.sounds, selectedCat, []);
            this.soundCategories.push({name: selectedCat, show: true});
            this.soundCategories.sort((a,b)=> a.name.localeCompare(b.name));
          }
          Array.prototype.push.apply(this.sounds[selectedCat],response.data);
          this.sounds[selectedCat].sort((a,b) => a.fileName.localeCompare(b.fileName));
          
          this.$bvToast.toast(`Gratuliere! Du hosts gschofft a Datei hochzulodn :thumbsup:`, {
              title: 'Erfolg',
              autoHideDelay: this.$config.toastDelay,
              variant: 'success',
              appendToast: true
            });
        }
        catch{
          this.$bvToast.toast(`Konn de Datei nit aufelodn ¯\\_(ツ)_/¯`, {
              title: 'Fehler',
              autoHideDelay: this.$config.toastDelay,
              variant: 'danger',
              appendToast: true
          });
        };
      }
      else{
        this.$refs.file.value = '';
        this.$bvToast.toast(`Gib bitte a Kategorie beim Upload on du Pliatz`, {
            title: 'Warnung',
            autoHideDelay: this.$config.toastDelay,
            variant: 'warning',
            appendToast: true
        });
      }
    },
    playFile(id){
      const audio = this.$refs[`audio_${id}`][0];
      if(!audio.src){
        dataservice.downloadSound(id).then(response =>{
          try{
            audio.pause();
            audio.src = URL.createObjectURL(response.data);
            audio.play();
          }
          catch{
            this.$bvToast.toast(`Konn de Datei nit obspüln\nFormat weat onscheinend nit unterstützt`, {
              title: 'Fehler',
              autoHideDelay: this.$config.toastDelay,
              variant: 'danger',
              appendToast: true
            });  
          }
        }).catch(()=>{
          this.$bvToast.toast(`Konn de Datei nit obspüln`, {
            title: 'Fehler',
            autoHideDelay: this.$config.toastDelay,
            variant: 'danger',
            appendToast: true
          });
        });
      }
    },
    downloadSound(soundId){
      dataservice.downloadSound(soundId).then(response =>{
        const url = window.URL.createObjectURL(response.data);
        const link = document.createElement('a');
        link.href = url;
        link.setAttribute('download', getFileNameOutOfHeader(response.headers));
        document.body.appendChild(link);
        link.click();
      }).catch(()=>{
        this.$bvToast.toast(`Konn de Datei nit obalodn`, {
            title: 'Fehler',
            autoHideDelay: this.$config.toastDelay,
            variant: 'danger',
            appendToast: true
          });
      });

      function getFileNameOutOfHeader(headers){
        let fileName = "";
        const disposition = headers['content-disposition'];
        if (disposition && disposition.indexOf('attachment') !== -1) {
            var reg = /filename[^;=\n]*=((['"]).*?\2|[^;\n]*)/;
            var matches = reg.exec(disposition);
            if (matches != null && matches[1]) { 
              fileName = matches[1].replace(/['"]/g, '');
            }
        }
        return fileName;
      }
    },
    fetchChannels(){
        return dataservice.fetchChannels(this.selectedServer).then(response =>{
            this.channels = response.data;
            this.selectedChannel = this.channels[0].id;
        }).catch(error => {
          this.$bvToast.toast(`Hob de Channels nit glodn. Meh... Probiers amfoch noch amol`, {
            title: 'Fehler',
            autoHideDelay: this.$config.toastDelay,
            variant: 'danger',
            appendToast: true
          });
        });
    },
    fetchSounds(){
      this.soundCategories = [];
      this.selectedCategory = '';
      dataservice.fetchSounds(this.selectedServer).then(response =>{
        this.sounds = {};
        response.data.forEach(sound =>{
          if(!this.sounds[sound.category]){
            this.$set(this.sounds, sound.category, []);
          }
          this.sounds[sound.category].push(sound);
        });
        this.setSoundCategories();
      }).catch(error =>{
        this.$bvToast.toast(`Konn de Sounds nit lodn. Frog Mr. Admin wos do vakehrt laft`, {
          title: 'Fehler',
          autoHideDelay: this.$config.toastDelay,
          variant: 'danger',
          appendToast: true
        });
      });
    },
    setSoundCategories(){
      this.soundCategories = Object.keys(this.sounds).sort((a,b) => a.localeCompare(b)).map(category =>({name: category, show: true})); //vue.js does not recognize new elements. that's why I have to add "show"
      this.selectedCategory = this.soundCategories.length > 0 ? this.soundCategories[0].name : '';
    },
    playSound(soundId, forcePlay){
      const data = {
        soundId,
        forcePlay,
        serverId: this.selectedServer,
        channelId: this.selectedChannel,
        volume: this.volume,
        joinUser: this.joinUser,
        url: this.youtubeUrl
      }
      dataservice.playSound(data).then(response =>{
        
      }).catch(error =>{
        let message = error.response.status === 400 ? 
        'Dir is schon klor, dass des "Join to User" nit funktioniert, wenn du in kan Channel bist oda?' :
        `Der Sound konn nit obgspült werdn. Very strange`
        
        this.$bvToast.toast(message, {
          title: 'Fehler',
          autoHideDelay: this.$config.toastDelay,
          variant: 'danger',
          appendToast: true
        });
      });
    },
    setIntro(soundId){
      dataservice.setIntro(soundId, undefined, this.selectedServer).then(()=>{
        this.$bvToast.toast('Intro gsetzt', {
          title: 'Erfolg',
          autoHideDelay: this.$config.toastDelay,
          variant: 'success',
          appendToast: true
        });
      }).catch(()=>{
        this.$bvToast.toast('Konn des Intro nit setzn', {
          title: 'Fehler',
          autoHideDelay: this.$config.toastDelay,
          variant: 'danger',
          appendToast: true
        });
      })
    },
    deleteSound(soundId, index, categoryName){
      dataservice.deleteSound(soundId).then(()=>{
        this.sounds[categoryName].splice(index,1);
        if(this.sounds[categoryName].length == 0){
          delete this.sounds[categoryName];
          let index = -1;
          this.soundCategories.forEach((category, $index) =>{
            if(category.name == categoryName){
              index = $index;
            }
          })
          if(index !== -1){
            this.soundCategories.splice(index,1);
          }
        }
        this.$bvToast.toast('Die Datei wurde gelöscht My Lord', {
          title: 'Erfolg',
          autoHideDelay: this.$config.toastDelay,
          variant: 'success',
          appendToast: true
        });
      }).catch(()=>{
        this.$bvToast.toast('I konn de Datei nit löschen ( ._.)', {
          title: 'Fehler',
          autoHideDelay: this.$config.toastDelay,
          variant: 'danger',
          appendToast: true
        });
      })
    },
    changeCategoryVisibility(category){
      category.show = !category.show;
    },
    setCategoriesVisibility(status){
      this.soundCategories.forEach(category =>(category.show = status));
    },
    updateWebsite(){
      dataservice.updateWebsite().then(response=>{
        this.$bvToast.toast(`Also Fehla gibts onscheinend kan. Des wär der Response\n ${response.data}`, {
          title: 'Information',
          autoHideDelay: this.$config.toastDelay,
          variant: 'info',
          appendToast: true
        });
      }).catch(error =>{
        this.$bvToast.toast(`Warum is do schon wieda a Fehla?`, {
            title: 'Fehler',
            autoHideDelay: this.$config.toastDelay,
            variant: 'danger',
            appendToast: true
          });
      });
    },
    stopPlaying(){
      dataservice.stopPlaying(this.selectedServer).then(response =>{
        this.$bvToast.toast(`Da Bot holtat jetz de Goschn`, {
          title: 'Erfolg',
          autoHideDelay: this.$config.toastDelay,
          variant: 'success',
          appendToast: true
        });
      }).catch(error =>{
        this.$bvToast.toast(`Der Bot wüll nit aufhean oda hot schon aufgheat?`, {
          title: 'Fehler',
          autoHideDelay: this.$config.toastDelay,
          variant: 'danger',
          appendToast: true
        });
      })
    },
    filteredSounds(categoryName){
      if(this.searchText.length > 0){
        const re = new RegExp(this.searchText,'i');
        return this.sounds[categoryName].filter(sound => re.test(sound.fileName) || re.test(sound.user.name));
      }
      else{
        return this.sounds[categoryName];
      }
    },
    containsServer(serverId){
      return this.arrayContainsId(this.servers,serverId);
    },
    containsChannel(channelId){
      return this.arrayContainsId(this.channels,channelId);
    },
    saveSettings(){
      const data = {
        selectedServer: this.selectedServer,
        selectedChannel: this.selectedChannel,
        joinUser: this.joinUser,
        volume: this.volume
      }
      settings.save(data);
    },
    loadSettings(){
      const data = settings.load();
      if(data){
        if(this.containsServer(data.selectedServer)){
          this.selectedServer = data.selectedServer;
          this.fetchChannels().then(response =>{
            if(this.containsChannel(data.selectedChannel)){
              this.selectedChannel = data.selectedChannel;
            }
          })
        }
        
        this.volume = data.volume;
        this.joinUser = data.joinUser;
      }
      else{
        this.fetchChannels();
      }
    },
    arrayContainsId(array, id){
      let status = false;
      for(let i = 0; i < array.length; i++){
        if(array[i].id == id){
          status = true;
          break;
        }
      }
      return status;
    }
  }
}
</script>

<style scoped>
.finger {
    cursor: pointer;
}

/*Action icons*/
table a i {
  font-size: 40px !important;
  padding-right: 10px;
}

a.disabled {
  pointer-events: none;
  cursor: default;
  color: gray;
}
</style>
